services:
  nats:
    image: nats:2.10
    container_name: nats-innsbruck
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    networks: [parking-innsbruck]

  camera:
    build:
      context: ./src/ticketless_parking_system/IoT/camera
    container_name: camera-innsbruck
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - CAR_PARK_ID=Parking_Innsbruck
      - CAMERA_ID=innsbruck_0
    depends_on: [nats]
    networks: [parking-innsbruck]
    volumes:
      - ./data:/app/data

  barrier-entry:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    container_name: barrier-entry-innsbruck
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=entry_innsbruck_0
    depends_on: [nats]
    networks: [parking-innsbruck]

  barrier-exit:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    container_name: barrier-exit-innsbruck
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=exit_innsbruck_0
    depends_on: [nats]
    networks: [parking-innsbruck]

  edge:
    build:
      context: ./src/ticketless_parking_system/edge
    container_name: edge-innsbruck
    restart: always
    environment:
      - EDGE_NATS_URL=nats://nats:4222
      - CLOUD_URL=http://54.167.216.74:8080
      - CLOUD_NATS_URL=nats://54.211.204.6:4222
      - DB_PATH=/app/data/parking.db
      - CAR_PARK_ID=Parking_Innsbruck
      - CAR_PARK_LAT=47.259659
      - CAR_PARK_LNG=11.400375
    depends_on: [nats, camera, barrier-entry, barrier-exit]
    networks: [parking-innsbruck]
    volumes:
      - edge-db-innsbruck:/app/data

networks:
  parking-innsbruck:
    driver: bridge

volumes:
  edge-db-innsbruck:
