services:
  nats:
    image: nats:2.10
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring UI
    environment:
      - JS_DISABLE=true
    command: ["-js"]   # enable JetStream if you want it
    networks:
      - parking-net

  camera:
    build:
      context: ./src/ticketless_parking_system/IoT/camera
    container_name: camera-simulator
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - CAMERA_ID=0
    depends_on:
      - nats
    networks:
      - parking-net
    volumes:
      - ./data:/app/data  # mount your image dataset

  edge-server:
    build:
      context: ./src/ticketless_parking_system/edge
    container_name: edge-server
    restart: always
    environment:
      - EDGE_NATS_URL=nats://nats:4222
      - CLOUD_NATS_URL=nats://nats:4222
      - DB_PATH=/app/data/parking.db
    depends_on:
      - nats
    networks:
      - parking-net
    volumes:
      # persistent storage for SQLite DB file
      - edge-db-data:/app/data

  cloud:
      build:
        context: ./src/ticketless_parking_system/cloud   # <-- adjust to your Dockerfile folder
      container_name: parking-system-cloud
      restart: always
      ports:
        - "8080:8080"
      environment:
        - PARKING_ENVIRONMENT=development
        - PARKING_ENABLE_METRICS=false
        - HTTP_PORT=8080
        - NATS_URL=nats://nats:4222
      depends_on:
        - nats
      networks:
        - parking-net

networks:
  parking-net:
    driver: bridge

volumes:
  edge-db-data: