services:
  nats:
    image: nats:2.10
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring UI
    environment:
      - JS_DISABLE=true
    command: ["-js"] # enable JetStream if you want it
    networks:
      - parking-net

  camera:
    build:
      context: ./src/ticketless_parking_system/IoT/camera
    container_name: camera-simulator
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - CAMERA_ID=0
    depends_on:
      - nats
    networks:
      - parking-net
    volumes:
      - ./data:/app/data # mount your image dataset

  barrier-entry:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=entry_0
    depends_on:
      - nats
    networks:
      - parking-net

  barrier-exit:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=exit_0
    depends_on:
      - nats
    networks:
      - parking-net

  dashboard:
    build:
      context: ./src/ticketless_parking_system/IoT/dashboard
    container_name: dashboard
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "8000:8000"
    depends_on:
      - nats
    networks:
      - parking-net

  edge-server:
    build:
      context: ./src/ticketless_parking_system/edge
    container_name: edge-server
    restart: always
    environment:
      - EDGE_NATS_URL=nats://nats:4222
      - CLOUD_URL=http://98.83.43.132:8080
      - CLOUD_NATS_URL=nats://44.221.89.68:4222
      - DB_PATH=/app/data/parking.db
    depends_on:
      - nats
    networks:
      - parking-net
    volumes:
      # persistent storage for SQLite DB file
      - edge-db-data:/app/data

networks:
  parking-net:
    driver: bridge

volumes:
  edge-db-data:
