services:
  nats:
    image: nats:2.10
    container_name: nats-salzburg
    restart: always
    ports:
      - "4225:4222"
      - "8225:8222"
    command: ["-js", "-m", "8222"]
    networks: [parking-salzburg]

  camera:
    build:
      context: ./src/ticketless_parking_system/IoT/camera
    container_name: camera-salzburg
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - CAR_PARK_ID=Parking_Salzburg
      - CAMERA_ID=salzburg_0
    depends_on: [nats]
    networks: [parking-salzburg]
    volumes:
      - ./data:/app/data

  barrier-entry:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    container_name: barrier-entry-salzburg
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=entry_salzburg_0
    depends_on: [nats]
    networks: [parking-salzburg]

  barrier-exit:
    build:
      context: ./src/ticketless_parking_system/IoT/barrier
    container_name: barrier-exit-salzburg
    restart: always
    environment:
      - NATS_URL=nats://nats:4222
      - BARRIER_ID=exit_salzburg_0
    depends_on: [nats]
    networks: [parking-salzburg]

  edge:
    build:
      context: ./src/ticketless_parking_system/edge
    container_name: edge-salzburg
    restart: always
    environment:
      - EDGE_NATS_URL=nats://nats:4222
      - CLOUD_URL=http://54.243.10.60:8080
      - CLOUD_NATS_URL=nats://3.87.211.209:4222
      - DB_PATH=/app/data/parking.db
      - CAR_PARK_ID=Parking_Salzburg
      - CAR_PARK_LAT=47.811195
      - CAR_PARK_LNG=13.033229
    depends_on: [nats, camera, barrier-entry, barrier-exit]
    networks: [parking-salzburg]
    volumes:
      - edge-db-salzburg:/app/data

networks:
  parking-salzburg:
    driver: bridge

volumes:
  edge-db-salzburg:
